version: "3"


services:

  production:
    image: richpotato/microblog:1.0.0-prod
    container_name: microblog
    ports: 
      - "8000:5000"
    environment: 
      DATABASE_URL: mysql+pymysql://microblog:password@mysql/microblog
    links:
      - database:mysql
    depends_on:
      - database
    restart:
      "always"

  database:
    image: mysql/mysql-server:5.7
    container_name: mysql
    volumes:
      - mysqldb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'microblog'
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: 'microblog'
      MYSQL_PASSWORD: 'password'
    restart:
      "always"

  tests:
    container_name: microblog-test
    image: richpotato/microblog:test
    volumes: 
      - ./app:/home/microblog/app
      - ./tests:/home/microblog/tests

volumes:
  mysqldb: