---
- name: update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes

- name: install packages
  apt: 
    name: "{{packages}}"
    state: present

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian buster stable
    state: present

- name: Install Docker Module for Python
  pip:
    name: "{{pip_install}}"
    state: present
    executable: pip3

- name: install docker requirements
  apt: 
    name: "{{docker_requirements}}"
    state: present
    update_cache: true