---
-   name: Create a Docker network
    docker_network:
        name: monitor

- name: log into docker hub
  docker_login:
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"

-   name: Grafana template
    template:
        src: templates/grafana.ini.j2
        dest: /tmp/grafana.ini
        force: yes

- name: start grafana
  docker_container:
    name: grafana
    image: grafana/grafana:8.2.4 
    restart_policy: unless-stopped
    volumes: 
      - grafana-data:/var/lib/grafana
      - /tmp/grafana.ini:/etc/grafana/grafana.ini
    network_mode: host
    ports:
      - "3000:3000"
    env:
      GF_SECURITY_ADMIN_PASSWORD: admin
