# syntax=docker/dockerfile:1.4
FROM python:3.8-alpine3.16

RUN <<-EOF
    apk add make=4.3-r0
    adduser -D microblog
EOF

WORKDIR /home/microblog

COPY requirements.txt test.sh Makefile pytest.ini microblog.py .coveragerc .pylintrc ./
COPY requirements requirements

RUN <<-EOF
    python -m venv venv
    venv/bin/pip3 install -r requirements/test.txt
    chown -R microblog:microblog ./
    chmod +x test.sh
EOF

# COPY migrations migrations
# COPY app app

VOLUME ["./app", "./tests"]

ENTRYPOINT ["./test.sh"]
#docker build -f docker/Dockerfile_test -t microblog:1.0.0-test .

#docker run --name microblog -p 8000:5000 -d --rm microblog1.0.0-prod
#docker logs microblog
#make.vr.0
#docker run --name microblog-test --rm microblog:1.0.0-test -v .

# docker run --name microblog-test --rm microblog:test -v ./app:/home/microblog/app -v ./tests:/home/microblog/tests