apiVersion: v1
kind: Service
metadata:
  name: microblog
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: microblog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog
specs:
  selector:
    matchLabels:
      app: microblog
  replicas: 2
  template:
    metadata:
      labels:
        app: microblog
    specs:
      containers:
        - image: richpotato/microblog:latest
          imagePullPolicy: Always
          name: microblog
          env:
            - name: SECRET_KEY
              value: password
            - name: DATABASE_URL
              value: mysql+pymysql://microblog:password@mysql/microblog
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000