apiVersion: v1
kind: Service
metadata:
  name: microblog
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: microblog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog
spec:
  selector:
    matchLabels:
      app: microblog
  replicas: 2
  template:
    metadata:
      labels:
        app: microblog
    spec:
      containers:
        - image: richpotato/microblog:latest
          imagePullPolicy: Always
          name: microblog
          env:
            - name: DATABASE_URL
              value: mysql+pymysql://microblog:micropassw@mysql/microblog
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000