---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  ROOT_PASSWORD: bXktc3VwZXItc2VjcmV0LXJvb3QtcGFzc3dvcmQ=
  DB_PASSWORD: bWljcm9wYXNzdw==
  # DATABASE_URL: bXlzcWwrcHlteXNxbDovL21pY3JvYmxvZzptaWNyb3Bhc3N3QG15c3FsOjMzMDYvbWljcm9ibG9n