---
# ansible-galaxy collection install community.docker
- name: log into docker hub
  docker_login:
    # email: "{{docker_email}}"
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"

- name: start container
  docker_container:
    name: mysql
    image: mysql/mysql-server:5.7
    volumes:
      - /mysqldb:/var/lib/mysql
    exposed_ports: 3306:3306
    env:
      MYSQL_DATABASE: "microblog"
      MYSQL_ROOT_PASSWORD: "{{mysql_root_password}}"
      MYSQL_USER: "microblog"
      MYSQL_PASSWORD: "{{ mysql_microblog_password }}"
    restart_policy: always