---
- name: log into docker hub
  docker_login:
    # email: "{{docker_email}}"
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"

- name: start container
  docker_container:
    name: microblog
    image: richpotato/microblog:flask-exporter
    ports: 
      - "8000:5000"
    env:
      DATABASE_URL: "mysql+pymysql://microblog:{{ mysql_microblog_password }}@{{ groups['database'][0] }}:3306/microblog"
    restart_policy: always
