name: "Snyk Python (3.8)"
description: "Check your Python application for vulnerabilties using Snyk"
author: "Gareth Rushgrove"
on: [push]
jobs:     
  snyk-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Specify Python version
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python-3.8@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_API_KEY }}
      with:
        args: --severity-threshold=high